name: Lewis Baker
email: lewisjbaker@gmail.com
url: "https://ljbaker.github.io" # the base hostname & protocol for your site
github_username:  ljbaker

markdown: kramdown

permalink: /blog/:year/:month/:day/:title
defaults:
  -
      layout:     "default"

theme: jekyll-theme-time-machine